<a href="https://colab.research.google.com/github/TranThanhBinh1/PythonTutorial/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
#create an array
#1d array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
#3d array
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#access element
print(a[1])
print(b[2,0])

2
7


In [6]:
#sorting array
c = np.array([23,45,78,12,3,57,23])
np.sort(c)

array([ 3, 12, 23, 23, 45, 57, 78])

In [20]:
 #concatenate arrays
 d = np.array([[1,2,3]])
 e = np.array([[4, 5, 6]])
 np.concatenate((d, e))


array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
x = np.array([[1, 2, 2], [3, 4, 4]])
y = np.array([[5, 6, 6]])
np.concatenate((x, e), axis=0)

array([[1, 2, 2],
       [3, 4, 4],
       [4, 5, 6]])

In [31]:
#Shape and size of an array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
p1 = array_example.ndim
p2 = array_example.size
p3 = array_example.shape
print(p1,"/",p2,"/",p3)

3 / 24 / (3, 2, 4)


In [35]:
#reshape array
p = np.arange(6)
p.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
np.reshape(p, newshape=(1, 6), order='F')

array([[0, 1, 2, 3, 4, 5]])

In [39]:
#Transpose
p.reshape(2,3).transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])